version: "3"

services:
  node-api:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=yucorrea
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=node-api
